# BlueBear Engine
blue_bear_engine:
    events:
        bluebear.hexagon.unit.select: ~
        bluebear.hexagon.unit.move: ~
        # all empty events descriptions will automatically default to clickRequest and mapUpdateResponse
    game:
        entity_type:
            unit:
                label: Unit
                description: Base unit (common logic to all units)
                class: BlueBear\HexagonBundle\Entity\Unit
                behaviors: [selectable_unit]
        # entity behaviors (and their associated event to listen)
        behaviors:
            selectable_unit: bluebear.hexagon.unit.select
