lag_admin:
    admins:
        pencil:
            entity: App\Entity\Map\Pencil
            actions:
                list: ~
                create: ~
                edit: ~
                delete: ~
