lag_admin:
    admins:
        pencil_set:
            entity: App\Entity\Map\PencilSet
            actions:
                menus: false
                list:
                    fields:
                        id: ~
                        name: ~
                create: ~
                edit: ~
                delete: ~
