parameters:
    # routing
    bluebear.admin.routing: BlueBear\AdminBundle\Routing\RoutingLoader
    # admin factory
    bluebear.admin.factory: BlueBear\AdminBundle\Admin\AdminFactory
    # menu factory
    bluebear.menu.factory: BlueBear\AdminBundle\Menu\MenuFactory

services:
    # routing
    bluebear.admin.routing:
        class: %bluebear.admin.routing%
        tags:
            - { name: routing.loader }
        calls:
            - [setContainer, [@service_container]]

    # factory
    bluebear.admin.factory:
        class: %bluebear.admin.factory%
        arguments: [@service_container]

    bluebear.menu.factory:
        class: %bluebear.menu.factory%
        arguments: [@service_container, @bluebear.admin.routing]