<?php

namespace BlueBear\CoreBundle\Entity\Game;

use Doctrine\ORM\EntityRepository;

/**
 * GameActionRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class GameActionRepository extends EntityRepository
{
}
