bluebear.dungeon.createCharacter:
    path:     /create/race
    defaults: { _controller: BlueBearDungeonBundle:Main:selectRace }

bluebear.dungeon.selectRace:
    path:     /create/race
    defaults: { _controller: BlueBearDungeonBundle:Main:selectRace }

bluebear.dungeon.selectClass:
    path:     /create/{race}/class
    defaults: { _controller: BlueBearDungeonBundle:Main:selectClass }

bluebear.dungeon.selectAttributes:
    path:     /create/{race}/{class}/attributes
    defaults: { _controller: BlueBearDungeonBundle:Main:selectAttributes }

bluebear.dungeon.selectSkills:
    path:     /create/{race}/{class}/skills
    defaults: { _controller: BlueBearDungeonBundle:Main:selectSkills }

bluebear.dungeon.selectProfile:
    path:     /create/{race}/{class}/skills/profile
    defaults: { _controller: BlueBearDungeonBundle:Main:selectProfile }
