parameters:
    bluebear.form.image_type: BlueBear\CoreBundle\Form\Editor\ImageType
    bluebear.form.pencil_type: BlueBear\CoreBundle\Form\Map\PencilType
    bluebear.form.pencil_set_type: BlueBear\CoreBundle\Form\Map\PencilSetType
    bluebear.form.layer_type: BlueBear\CoreBundle\Form\Map\LayerType
    bluebear.form.image_list_type: BlueBear\CoreBundle\Form\Editor\ImageListType

services:
    # entity
    bluebear.form.image_type:
        class: %bluebear.form.image_type%
        tags:
            - { name: form.type, alias: image }

    bluebear.form.pencil_type:
        class: %bluebear.form.pencil_type%
        tags:
            - { name: form.type, alias: pencil }
        calls:
            - [setLayerManager, [@bluebear.manager.layer]]
            - [setImageManager, [@bluebear.manager.image]]

    bluebear.form.pencil_set_type:
        class: %bluebear.form.pencil_set_type%
        tags:
            - { name: form.type, alias: pencil_set }

    bluebear.form.layer_type:
        class: %bluebear.form.layer_type%
        tags:
            - { name: form.type, alias: layer }

    # utils
    bluebear.form.image_list_type:
        class: %bluebear.form.image_list_type%
        tags:
            - { name: form.type, alias: image_list }
        calls:
            - [setImageManager, [@bluebear.manager.image]]