parameters:
    bluebear.form.image_type: BlueBear\CoreBundle\Form\Editor\ImageType

services:
    bluebear.form.image_type:
        class: %bluebear.form.image_type%
        tags:
            - { name: form.type, alias: image }