parameters:
    bluebear.form.pencil_type: BlueBear\CoreBundle\Form\Map\PencilType
    bluebear.form.pencil_set_type: BlueBear\CoreBundle\Form\Map\PencilSetType
    bluebear.form.pencil_set_list_type: BlueBear\CoreBundle\Form\Map\PencilSetListType
    bluebear.form.layer_type: BlueBear\CoreBundle\Form\Map\LayerType
    bluebear.form.map_type: BlueBear\CoreBundle\Form\Map\MapType
    bluebear.form.resource_type: BlueBear\CoreBundle\Form\Editor\ResourceType
    bluebear.form.resource_image_type: BlueBear\CoreBundle\Form\Editor\ImageType
    bluebear.form.engine_event_test_type: BlueBear\CoreBundle\Form\Engine\EngineEventTestType

services:
    # PencilType
    bluebear.form.pencil_type:
        class: %bluebear.form.pencil_type%
        tags:
            - { name: form.type, alias: pencil }
        calls:
            - [setLayerManager, [@bluebear.manager.layer]]
            - [setImageManager, [@bluebear.manager.image]]
            - [setPencilSetManager, [@bluebear.manager.pencil_set]]

    # PencilSetType
    bluebear.form.pencil_set_list_type:
        class: %bluebear.form.pencil_set_list_type%
        tags:
            - { name: form.type, alias: pencil_set_list }

    # PencilSetListType
    bluebear.form.pencil_set_type:
        class: %bluebear.form.pencil_set_type%
        tags:
            - { name: form.type, alias: pencil_set }

    # LayerType
    bluebear.form.layer_type:
        class: %bluebear.form.layer_type%
        tags:
            - { name: form.type, alias: layer }

    # MapType
    bluebear.form.map_type:
        class: %bluebear.form.map_type%
        tags:
            - { name: form.type, alias: map }
        calls:
            - [setPencilSetManager, [@bluebear.manager.pencil_set]]
            - [setLayerManager, [@bluebear.manager.layer]]

    # Resources (uploadable entities)
    bluebear.form.resource:
        class: %bluebear.form.resource_type%
        tags:
            - { name: form.type, alias: resource }
    bluebear.form.resource_image:
        class: %bluebear.form.resource_image_type%
        tags:
            - { name: form.type, alias: resource_image }

    # utils
    bluebear.form.engine_event_test_type:
        class: %bluebear.form.engine_event_test_type%
        tags:
            - { name: form.type, alias: engine_event_test }
