parameters:
    bluebear.form.image_type: BlueBear\CoreBundle\Form\Editor\ImageType
    bluebear.form.pencil_type: BlueBear\CoreBundle\Form\Map\PencilType
    bluebear.form.pencil_set_type: BlueBear\CoreBundle\Form\Map\PencilSetType
    bluebear.form.pencil_set_list_type: BlueBear\CoreBundle\Form\Map\PencilSetListType
    bluebear.form.layer_type: BlueBear\CoreBundle\Form\Map\LayerType
    bluebear.form.map_type: BlueBear\CoreBundle\Form\Map\MapType
    bluebear.form.image_list_type: BlueBear\CoreBundle\Form\Editor\ImageListType
    bluebear.form.upload_type: BlueBear\CoreBundle\Form\Editor\UploadType

services:
    # ImageType
    bluebear.form.image_type:
        class: %bluebear.form.image_type%
        tags:
            - { name: form.type, alias: image }

    # PencilType
    bluebear.form.pencil_type:
        class: %bluebear.form.pencil_type%
        tags:
            - { name: form.type, alias: pencil }
        calls:
            - [setLayerManager, [@bluebear.manager.layer]]
            - [setImageManager, [@bluebear.manager.image]]

    # PencilSetType
    bluebear.form.pencil_set_list_type:
        class: %bluebear.form.pencil_set_list_type%
        tags:
            - { name: form.type, alias: pencil_set_list }

    # PencilSetListType
    bluebear.form.pencil_set_type:
        class: %bluebear.form.pencil_set_type%
        tags:
            - { name: form.type, alias: pencil_set }

    # LayerType
    bluebear.form.layer_type:
        class: %bluebear.form.layer_type%
        tags:
            - { name: form.type, alias: layer }

    # MapType
    bluebear.form.map_type:
        class: %bluebear.form.map_type%
        tags:
            - { name: form.type, alias: map }
        calls:
            - [setPencilSetManager, [@bluebear.manager.pencil_set]]

    # UploadType
    bluebear.form.upload:
        class: %bluebear.form.upload_type%
        tags:
            - { name: form.type, alias: upload }

    # utils
    bluebear.form.image_list_type:
        class: %bluebear.form.image_list_type%
        tags:
            - { name: form.type, alias: image_list }
        calls:
            - [setImageManager, [@bluebear.manager.image]]