parameters:
    bluebear.manager.image: BlueBear\CoreBundle\Manager\ImageManager
    bluebear.manager.item: BlueBear\CoreBundle\Manager\ItemManager
    bluebear.manager.pencil: BlueBear\CoreBundle\Manager\PencilManager
    bluebear.manager.pencil_set: BlueBear\CoreBundle\Manager\PencilSetManager
    bluebear.manager.layer: BlueBear\CoreBundle\Manager\LayerManager
    bluebear.manager.map: BlueBear\CoreBundle\Manager\MapManager
    bluebear.manager.resource: BlueBear\CoreBundle\Manager\ResourceManager

services:
    # ImageManager
    bluebear.manager.image:
        class: %bluebear.manager.image%
        calls:
            - [setContainer, [@service_container]]

    # PencilManager
    bluebear.manager.pencil:
        class: %bluebear.manager.pencil%
        calls:
            - [setContainer, [@service_container]]

    # PencilSetManager
    bluebear.manager.pencil_set:
        class: %bluebear.manager.pencil_set%
        calls:
            - [setContainer, [@service_container]]

    # ItemManager
    bluebear.manager.item:
        class: %bluebear.manager.item%
        calls:
            - [setContainer, [@service_container]]

    # LayerManager
    bluebear.manager.layer:
            class: %bluebear.manager.layer%
            calls:
                - [setContainer, [@service_container]]

    # MapManager
    bluebear.manager.map:
            class: %bluebear.manager.map%
            calls:
                - [setContainer, [@service_container]]

    # ResourceManager
    bluebear.manager.resource:
            class: %bluebear.manager.resource%
            calls:
                - [setContainer, [@service_container]]