parameters:
    bluebear.manager.image: BlueBear\CoreBundle\Manager\ImageManager
    bluebear.manager.pencil: BlueBear\CoreBundle\Manager\PencilManager
    bluebear.manager.pencil_set: BlueBear\CoreBundle\Manager\PencilSetManager
    bluebear.manager.layer: BlueBear\CoreBundle\Manager\LayerManager
    bluebear.manager.map: BlueBear\CoreBundle\Manager\MapManager
    bluebear.manager.map_item: BlueBear\CoreBundle\Manager\MapItemManager
    bluebear.manager.context: BlueBear\CoreBundle\Manager\ContextManager
    bluebear.manager.game: BlueBear\CoreBundle\Manager\GameManager

services:
    # ImageManager
    bluebear.manager.image:
        class: %bluebear.manager.image%
        calls:
            - [setContainer, [@service_container]]

    # PencilManager
    bluebear.manager.pencil:
        class: %bluebear.manager.pencil%
        calls:
            - [setContainer, [@service_container]]

    # PencilSetManager
    bluebear.manager.pencil_set:
        class: %bluebear.manager.pencil_set%
        calls:
            - [setContainer, [@service_container]]

    # LayerManager
    bluebear.manager.layer:
        class: %bluebear.manager.layer%
        calls:
            - [setContainer, [@service_container]]

    # MapManager
    bluebear.manager.map:
        class: %bluebear.manager.map%
        calls:
            - [setContainer, [@service_container]]

    # MapItemManager
    bluebear.manager.map_item:
        class: %bluebear.manager.map_item%
        calls:
            - [setContainer, [@service_container]]

    # ContextManager
    bluebear.manager.context:
        class: %bluebear.manager.context%
        calls:
            - [setContainer, [@service_container]]

    # GameManager
    bluebear.manager.game:
        class: %bluebear.manager.game%
        calls:
            - [setContainer, [@service_container]]
