imports:
    - { resource: managers.yml }
    - { resource: forms.yml }

parameters:
    bluebear.path.finder: BlueBear\CoreBundle\Path\PathFinder

services:
    bluebear.path.finder:
        class: %bluebear.path.finder%
