# Map
BlueBear\CoreBundle\Entity\Map\Map:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name

# Pencil Set
BlueBear\CoreBundle\Entity\Map\PencilSet:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name