bluebear:
    engine:
        behaviors:
            positionable:
                class: App\Entity\Engine\Behaviors\PositionBehavior
            movable:
                class: App\Entity\Engine\Behaviors\MovementBehavior
                depends:
                    - positionable
