lag_admin:
    application:
        title: BlueBear, pyscho panda and maximum bamboo
        description: BlueBear, pandas, bamboo and energy drink
        bootstrap: true
        base_template: 'BlueBearBackofficeBundle::layout.html.twig'
        routing:
            name_pattern: 'bluebear.admin.{admin}.{action}'
            url_pattern: '{admin}/{action}'
    admins:
        map:
            entity: BlueBear\CoreBundle\Entity\Map\Map
            form: BlueBear\CoreBundle\Form\Type\Map\MapType
            actions: ~
        layer:
            entity: BlueBear\CoreBundle\Entity\Map\Layer
            form: BlueBear\CoreBundle\Form\Map\LayerType
        pencil_set:
            entity: BlueBear\CoreBundle\Entity\Map\PencilSet
            form: BlueBear\CoreBundle\Form\Map\PencilSetType
            actions: ~
        fireman:
            entity: BlueBear\FireBundle\Entity\EAVEntity
            form: Sidus\EAVModelBundle\Form\Type\DataType
            data_provider: 'lag.admin.eav_bridge.data_provider'

lag_admin_eav_bridge:
    entity: BlueBear\FireBundle\Entity\EAVEntity
    mapping:
        # admin: EAV Family
        fireman: FireMan
