bluebear_editor_homepage:
    path:  /editor
    defaults: { _controller: 'BlueBearEditorBundle:Main:index' }

bluebear_map_edit:
    path:  /editor/map
    defaults: { _controller: 'BlueBearEditorBundle:Main:edit' }

bluebear_map_delete:
    path:  /editor/delete/{id}
    defaults: { _controller: 'BlueBearEditorBundle:Main:delete' }
