parameters:
    bluebear.menu.menu_subscriber:  BlueBear\MenuBundle\Event\MenuSubscriber
    # menu factory
    bluebear.menu.factory: BlueBear\MenuBundle\Menu\MenuFactory

services:
    bluebear.menu.menu_subscriber:
        class: '%bluebear.menu.menu_subscriber%'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: kernel.event_subscriber}
    # menu factory
    bluebear.menu.factory:
        class: '%bluebear.menu.factory%'
        arguments: ['@service_container', '@bluebear.admin.routing']
