App\Entity\Engine\Behaviors\PositionBehavior:
    type: entity
    table: behavior_position
    repositoryClass: App\Repository\Engine\MovementPositionRepository

    id:
        id:
            type: integer
            generator:
                strategy: auto

    fields:
        reference:
            type: guid
        x:
            type: integer
        y:
            type: integer
        z:
            type: integer
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update

    oneToOne:
        gameObject:
            targetEntity: App\Entity\Engine\GameObject
