App\Entity\Engine\GameObject:
    type: entity
    table: game_object
    repositoryClass: App\Repository\Engine\GameObjectRepository

    id:
        id:
            type: integer
            generator:
                strategy: auto

    fields:
        type:
            type: string
        reference:
            type: guid
        description:
            type: text
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update

    manyToMany:
        behaviors:
            targetEntity: App\Entity\Engine\GameBehavior
            indexBy: name
            joinTable:
                name: behave
