App\Entity\Engine\Behaviors\MovementBehavior:
    type: entity
    table: behavior_movement
    repositoryClass: App\Repository\Engine\GameBehaviorRepository

    id:
        id:
            type: integer
            generator:
                strategy: auto

    fields:
        reference:
            type: guid
        x:
            type: integer
        y:
            type: integer
        z:
            type: integer
        movement:
            type: integer
        movementMax:
            type: integer
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update

    oneToOne:
        gameObject:
            targetEntity: App\Entity\Engine\GameObject
