App\Entity\Map\Context:
    type: entity
    table: map_context
    repositoryClass: App\Entity\Map\ContextRepository

    id:
        id:
            type: integer
            generator:
                strategy: auto
    fields:
        label:
            type: string
        data:
            type: array
        version:
            type: integer
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update

    manyToMany:
        users:
            targetEntity: App\Entity\User\User
            mappedBy: contexts
    manyToOne:
        map:
            targetEntity: App\Entity\Map\Map
            fetch: EAGER
            inversedBy: contexts
    oneToMany:
        mapItems:
            targetEntity: App\Entity\Map\MapItem
            mappedBy: context
