App\Entity\Map\Layer:
    type: entity
    table: layer
    repositoryClass: App\Repository\Map\LayerRepository

    id:
        id:
            type: integer
            generator:
                strategy: auto
    fields:
        name:
            type: string
        label:
            type: string
        description:
            type: text
        index:
            column: z_index
            type: integer
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        type:
            type: string

    oneToMany:
        mapItems:
            targetEntity: App\Entity\Map\MapItem
            mappedBy: layer
