parameters:
    bluebear.form.entity_instance: BlueBear\GameBundle\Form\EntityInstanceType
    bluebear.form.entity_model: BlueBear\GameBundle\Form\EntityModelType
    bluebear.form.entity_instance_attribute: BlueBear\GameBundle\Form\EntityInstanceAttributeType
    bluebear.form.entity_model_attribute: BlueBear\GameBundle\Form\EntityModelAttributeType

services:
    bluebear.form.entity_instance:
        class: %bluebear.form.entity_instance%
        tags:
            - { name: form.type, alias: entity_instance }

    bluebear.form.entity_model:
        class: %bluebear.form.entity_model%
        tags:
            - { name: form.type, alias: entity_model }

    bluebear.form.attribute:
        class: %bluebear.form.entity_instance_attribute%
        tags:
            - { name: form.type, alias: entity_instance_attribute }

    bluebear.form.model:
        class: %bluebear.form.entity_model_attribute%
        tags:
            - { name: form.type, alias: entity_model_attribute }