parameters:
    # instances
    bluebear.form.entity_instance: BlueBear\GameBundle\Form\EntityInstanceType
    bluebear.form.entity_instance_attribute: BlueBear\GameBundle\Form\EntityInstanceAttributeType
    # models
    bluebear.form.entity_model: BlueBear\GameBundle\Form\EntityModelType
    bluebear.form.entity_model_attribute: BlueBear\GameBundle\Form\EntityModelAttributeType
    # generic
    bluebear.form.attribute_collection: BlueBear\GameBundle\Form\AttributeCollectionType

services:
    bluebear.form.entity_instance:
        class: %bluebear.form.entity_instance%
        tags:
            - { name: form.type, alias: entity_instance }

    bluebear.form.entity_model:
        class: %bluebear.form.entity_model%
        tags:
            - { name: form.type, alias: entity_model }
        calls:
            - [setEntityTypeFactory, [@bluebear.game.entity_type_factory]]

    bluebear.form.entity_instance_attribute:
        class: %bluebear.form.entity_instance_attribute%
        tags:
            - { name: form.type, alias: entity_instance_attribute }

    bluebear.form.entity_model_model:
        class: %bluebear.form.entity_model_attribute%
        tags:
            - { name: form.type, alias: entity_model_attribute }

    bluebear.form.attribute_collection:
        class: %bluebear.form.attribute_collection%
        tags:
            - { name: form.type, alias: attribute_collection }