parameters:
    bluebear.form.unit_instance: BlueBear\GameBundle\Form\UnitInstanceType
    bluebear.form.unit_instance_attribute: BlueBear\GameBundle\Form\UnitInstanceAttributeType

services:
    bluebear.form.unit_instance:
        class: %bluebear.form.unit_instance%
        tags:
            - { name: form.type, alias: unit_instance }

    bluebear.form.attribute:
        class: %bluebear.form.unit_instance_attribute%
        tags:
            - { name: form.type, alias: unit_instance_attribute }