parameters:
    bluebear.manager.entity_instance: BlueBear\GameBundle\Manager\EntityInstanceManager
    bluebear.manager.entity_model: BlueBear\GameBundle\Manager\EntityModelManager

services:
    bluebear.manager.entity_instance:
        class: %bluebear.manager.entity_instance%
        calls:
            - [setContainer, [@service_container]]

    bluebear.manager.entity_model:
        class: %bluebear.manager.entity_model%
        calls:
            - [setContainer, [@service_container]]