# Entities
bluebear_backoffice_entity:
    pattern: /entities
    defaults: { _controller: BlueBearGameBundle:Entity:index }

# Entities instances
bluebear_backoffice_entity_instance_create:
    pattern: /entities/instances/create
    defaults: { _controller: BlueBearGameBundle:Entity:createInstance }

bluebear_backoffice_entity_instance_edit:
    pattern: /entities/instances/edit/{id}
    defaults: { _controller: BlueBearGameBundle:Entity:editInstance }

bluebear_backoffice_entity_instance_delete:
    pattern: /entities/instances/delete/{id}
    defaults: { _controller: BlueBearGameBundle:Entity:deleteInstance }

# Entities models
bluebear_backoffice_entity_model_create:
    pattern: /entities/models/create
    defaults: { _controller: BlueBearGameBundle:Entity:createModel }


bluebear_backoffice_entity_model_edit:
    pattern: /entities/models/edit/{id}
    defaults: { _controller: BlueBearGameBundle:Entity:editModel }

bluebear_backoffice_entity_model_delete:
    pattern: /entities/models/delete/{id}
    defaults: { _controller: BlueBearGameBundle:Entity:deleteModel }