# Units
bluebear_backoffice_unit:
    pattern: /units
    defaults: { _controller: BlueBearGameBundle:Unit:index }

bluebear_backoffice_unit_edit:
    pattern: /units/edit
    defaults: { _controller: BlueBearGameBundle:Unit:edit }