imports:
    - { resource: managers.yml }
    - { resource: forms.yml }

parameters:
    # entity factory
    bluebear.game.entity_factory: BlueBear\GameBundle\Factory\EntityFactory
    # events subscribers
    bluebear.engine.event.mapitem_subscriber: BlueBear\GameBundle\Event\MapItem\MapItemSubscriber
    bluebear.engine.event.entity_subscriber: BlueBear\GameBundle\Event\Entity\EntitySubscriber

services:
    # factory
    bluebear.game.entity_factory:
        class: %bluebear.game.entity_factory%
        calls:
            - [setContainer, [@service_container]]
            - [setEntityTypes, [%bluebear.game.entity_type%, %bluebear.game.attribute%]]

    # events subscribers
    bluebear.engine.event.mapitem_subscriber:
        class: %bluebear.engine.event.mapitem_subscriber%
        tags:
            - {name: kernel.event_subscriber}
        calls:
            - [setContainer, [@service_container]]

    bluebear.engine.event.entity_subscriber:
        class: %bluebear.engine.event.entity_subscriber%
        tags:
            - {name: kernel.event_subscriber}
        calls:
            - [setContainer, [@service_container]]
