imports:
    - { resource: managers.yml }
    - { resource: forms.yml }

parameters:
    # events subscribers
    bluebear.engine.event.mapitem_subscriber: BlueBear\GameBundle\Event\MapItem\MapItemSubscriber

services:
    # events subscribers
    bluebear.engine.event.mapitem_subscriber:
        class: %bluebear.engine.event.mapitem_subscriber%
        tags:
            - {name: kernel.event_subscriber}
        calls:
            - [setContainer, [@service_container]]
