imports:
    - { resource: managers.yml }
    - { resource: forms.yml }

services:
#    blue_bear_game.example:
#        class: BlueBear\GameBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
