parameters:
    # events subscribers
    bluebear.game.event.mapitem_subscriber: BlueBear\GameBundle\Event\MapItem\MapItemSubscriber
    bluebear.game.event.entity_subscriber: BlueBear\GameBundle\Event\Entity\EntitySubscriber

services:
    # events subscribers
    bluebear.game.event.mapitem_subscriber:
        class: '%bluebear.game.event.mapitem_subscriber%'
        tags:
            - {name: kernel.event_subscriber}
        calls:
            - [setContainer, ['@service_container']]

    bluebear.game.event.entity_subscriber:
        class: '%bluebear.game.event.entity_subscriber%'
        tags:
            - {name: kernel.event_subscriber}
        calls:
            - [setContainer, ['@service_container']]
