blue_bear_action:
    base_entity:
        class: BlueBear\CoreBundle\Entity\BaseAction
        route: bluebear_{$class}_{$action}
        permissions: [ROLE_USER]
        actions:
            show:
              icon: icon-eye-open
            edit:
              icon: icon-pencil
            delete:
              icon: icon-trash
