#
# bluebear admin
#
# all properties marked as default can be removed. It is here for the example
blue_bear_admin:
    # main layout
    layout: BlueBearBackofficeBundle::layout.html.twig
    # block layout (by default)
    blocks_template: BlueBearAdminBundle:Form:fields.html.twig
    # list of managed admins
    admins:
        # entities
        pencil:
            # orm entity class
            entity: BlueBear\CoreBundle\Entity\Map\Pencil
            # associated form type
            form: pencil
            # associated controller (by default)
            controller: BlueBearAdminBundle:Generic
            # availables actions (by default)
            actions:
                list:
                    title: Pencils list
                    permissions: [ROLE_ADMIN, ROLE_USER]
                    # available fields for this action
                    fields:
                        id: ~
                        name: ~
                        label: ~
                        # displayed only 50 first characters in list action
                        description: {length: 50}
                create: ~
                edit: ~
                delete: ~
        pencil_set:
            # orm entity class
            entity: BlueBear\CoreBundle\Entity\Map\PencilSet
            # associated form type
            form: pencil_set
