imports:
    - { resource: config.yml }
    - { resource: '@SidusEAVModelBundle/Resources/config/services/annotation_generator.yml' }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: rotating_file
            max_files: 5
            path: "%kernel.logs_dir%/%kernel.environment%-front.log"
            level: error
