imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: security.yml }
    #- { resource: admins.yml }
    - { resource: admin/admin.yml }
    - { resource: admin/menu.yml }
    - { resource: game.yml }
    - { resource: actions.yml }
    - { resource: eav/model.yml }
    #- { resource: fileupload.yml }

# Symfony Configuration
framework:
    #esi:             ~
    translator:      { fallback: fr }
    secret:          '%secret%'
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: fr
    trusted_proxies: ~
    session:
        cookie_lifetime:    3600
    fragments:  ~
    serializer: ~

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - bootstrap_3_layout.html.twig

        # Custom
        - BlueBearCoreBundle:Form:fields.html.twig

# Monolog Configuration
monolog:
    handlers:
        main:
            type: rotating_file
            max_files: 5
            path: "%kernel.logs_dir%/bluebear-%kernel.environment%.log"
            level: error

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:     { type: memory }

services:
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

# Mopa
#mopa_bootstrap:
#    form: ~

# FOS User
#fos_user:
#    db_driver: orm
#    firewall_name: main
#    user_class: BlueBear\UserBundle\Entity\User

# JMS Serializer naming strategy
parameters:
    jms_serializer.serialized_name_annotation_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

# ElephantIO
#nc_elephant_io:
#    clients:
#        default:
#            connection: '%socket_io_server%'
#            version: 1.x
