# one uploader
oneup_uploader:
    mappings:
        image:
            frontend: blueimp
            allowed_mimetypes: [ "image/jpg", "image/jpeg", "image/png", "image/gif" ]
            storage:
                directory: '%kernel.root_dir%/../web/resources/images'
