# BlueBear Engine
blue_bear_engine:
    events:
        bluebear.engine.mapLoad:
            request: BlueBear\EngineBundle\Event\Map\LoadContextRequest
            response: BlueBear\EngineBundle\Event\Map\LoadContextResponse
        bluebear.engine.mapItemClick:
            request: BlueBear\EngineBundle\Event\MapItem\MapItemClickRequest
            response: BlueBear\EngineBundle\Event\MapItem\MapItemClickResponse
        bluebear.editor.putPencil:
            request: BlueBear\EditorBundle\Event\Map\PutPencilRequest
            response: BlueBear\EditorBundle\Event\Map\PutPencilResponse

# BlueBear Game
blue_bear_game:
    entity_type:
        door:
            label: Door
            attributes: [hp, armor]
            description: A way to go into another room
        unit:
            label: Unit
            attributes: [hp, race, class, intelligence, dexterity, force, movement]
            description: Unit on map (panda or foes)
        # item container represents a item which can holding other items, like a chest
        item_container:
            label: ItemContainer
            attributes: [hp, armor]
            description: An item container can hold other items, like a chest...
        item:
            label: Item
            attributes: [hp, armor]
            description: An item on the map
        weapon:
            label: Weapon
            attributes: [hp, armor]
            description: A weapon to deal damage
    attribute:
        # race, class
        race: {label: bluebear.attributes.race, type: string}
        class: {label: bluebear.attributes.class, type: string}
        armor: {label: bluebear.attributes.armor, type: int}
        # attack and defence are calculated from dexterity and force
        hp: {label: bluebear.attributes.hit_point, type: int}
        intelligence: {label: bluebear.attributes.intelligence, type: int}
        dexterity: {label: bluebear.attributes.dexterity, type: int}
        force: {label: bluebear.attributes.force, type: int}
        level: {label: bluebear.attributes.level, type: int}
        # movement
        movement: {label: bluebear.attributes.movement, type: int}