blue_bear_game:
    entity_type:
        door:
            attributes: [hp, armor]
        unit:
            attributes: [hp, race, class, intelligence, dexterity, force]
        # item container represents a item which can holding other items, like a chest
        item_container:
            attributes: [hp, armor]
        item:
            attributes: [hp, armor]
        weapon:
    attribute:
        # race, class
        race: {label: bluebear.attributes.race, type: string}
        class: {label: bluebear.attributes.class, type: string}
        # attack and defence are calculated from dexterity and force
        hp: {label: bluebear.attributes.hit_point, type: int}
        intelligence: {label: bluebear.attributes.intelligence, type: int}
        dexterity: {label: bluebear.attributes.dexterity, type: int}
        force: {label: bluebear.attributes.force, type: int}
        level: {label: bluebear.attributes.level, type: int}