blue_bear_core:
    resource: "@BlueBearCoreBundle/Resources/config/routing.yml"
    prefix:   /

blue_bear_editor:
    resource: "@BlueBearEditorBundle/Resources/config/routing.yml"
    prefix:   /

blue_bear_backoffice:
    resource: "@BlueBearBackofficeBundle/Resources/config/routing.yml"
    prefix:   /