# PHP engine
blue_bear_engine:
    resource: "@BlueBearEngineBundle/Resources/config/routing.yml"
    prefix:   /

# BlueBear Editor
blue_bear_editor:
    resource: "@BlueBearEditorBundle/Resources/config/routing.yml"
    prefix:   /

# BlueBear Core
blue_bear_core:
    resource: "@BlueBearCoreBundle/Resources/config/routing.yml"
    prefix:   /

# BlueBear AdminBundle
blue_bear_admin:
    resource: .
    type: extra

# BlueBear Backoffice
blue_bear_backoffice:
    resource: "@BlueBearBackofficeBundle/Resources/config/routing.yml"
    prefix:   /

# BlueBear Game
blue_bear_game:
    resource: "@BlueBearGameBundle/Resources/config/routing.yml"
    prefix:   /

# File upload (includes oneup routing)
blue_bear_file_upload:
    resource: "@BlueBearFileUploadBundle/Resources/config/routing.yml"
    prefix:   /


# User Security
blue_bear_user:
    resource: "@BlueBearUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
