lag_admin_eav_bridge:
    resource: "@LAGAdminEAVBridgeBundle/Resources/config/routing.yml"
    prefix:   /

# Guard
login:
    path: /login
    defaults: {_controller: 'BlueBearBackofficeBundle:Guard:login'}

login_check:
    path: /login_check
    defaults: {_controller: 'BlueBearBackofficeBundle:Guard:loginCheck'}

logout:
    path: /logout

# LAG Admin
lag_admin:
    resource: .
    prefix: /
    type: extra

blue_bear_fire:
    resource: "@BlueBearFireBundle/Resources/config/routing.yml"
    prefix:   /fire

blue_bear_dungeon:
    resource: "@BlueBearDungeonBundle/Resources/config/routing.yml"
    prefix:   /dungeon

# PHP engine
blue_bear_engine:
    resource: "@BlueBearEngineBundle/Resources/config/routing.yml"
    prefix:   /

# BlueBear Editor
blue_bear_editor:
    resource: "@BlueBearEditorBundle/Resources/config/routing.yml"
    prefix:   /

# BlueBear Core
blue_bear_core:
    resource: "@BlueBearCoreBundle/Resources/config/routing.yml"
    prefix:   /

# BlueBear Backoffice
blue_bear_backoffice:
    resource: "@BlueBearBackofficeBundle/Resources/config/routing.yml"
    prefix:   /

# BlueBear Game
blue_bear_game:
    resource: "@BlueBearGameBundle/Resources/config/routing.yml"
    prefix:   /BlueBearTest

