# PHP engine
blue_bear_engine:
    resource: "@BlueBearEngineBundle/Resources/config/routing.yml"
    prefix:   /

# BlueBear editor
blue_bear_editor:
    resource: "@BlueBearEditorBundle/Resources/config/routing.yml"
    prefix:   /

# BlueBear editor
blue_bear_core:
    resource: "@BlueBearCoreBundle/Resources/config/routing.yml"
    prefix:   /

# BlueBear backoffice
blue_bear_backoffice:
    resource: "@BlueBearBackofficeBundle/Resources/config/routing.yml"
    prefix:   /

# BlueBear backoffice
blue_bear_game:
    resource: "@BlueBearGameBundle/Resources/config/routing.yml"
    prefix:   /

# User security
blue_bear_user:
    resource: "@BlueBearUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

oneup_uploader:
    resource: .
    type: uploader

# BlueBear AdminBundle
blue_bear_admin:
    resource: .
    type: extra