version: '2'

services:
    app:
        image: alpine
        command: 'true'
        volumes:
            - '../:/var/www/current'

    www:
        build: www
        working_dir: /var/www/current
        depends_on:
            - mysql
            - mailcatcher
            - socketio
            - jikpoze
        ports:
            - ${WWW_PORT}:80
        volumes_from:
            - app
        volumes:
            - ./www/nginx/sites-available/:/etc/nginx/sites-available/
            - ${SSH_AUTH_SOCK}:/ssh-agent
        environment:
            SF_DATABASE_HOST: mysql
            SF_DATABASE_PORT: 3306
            SF_DATABASE_NAME: ${MYSQL_DATABASE}
            SF_DATABASE_USER: ${MYSQL_USER}
            SF_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
            SF_MAILER_TRANSPORT: smtp
            SF_MAILER_HOST: 'mailcatcher:1025'
            SF_MAILER_USER: '~'
            SF_MAILER_PASSWORD: '~'
            SF_LOCALE: en
            SF_SECRET: ${SF_SECRET}
            SF_SOCKET_IO_SERVER: 'socketio:3000'
            SF_SOCKET_IO_EXTERNAL_URI: 'http://${APP_HOSTNAME}:${SOCKETIO_PORT}'
            SF_DART_PORT: ${DART_PORT}

    mysql:
        image: mariadb
        ports:
            - ${DB_PORT}:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    dart:
        image: google/dart:1
        working_dir: /app
        volumes:
            - '../jikpoze/:/app/'
            - '../.dart-cache/:/root/.pub-cache/'
        command: ['pub', 'get']

    socketio:
        image: google/dart:1
        working_dir: /app
        depends_on:
            - dart
        ports:
            - ${SOCKETIO_PORT}:3000
        volumes:
            - '../jikpoze/:/app/'
            - '../.dart-cache/:/root/.pub-cache/'
        command: ['pub', 'run', 'jikpoze']

    jikpoze:
        image: google/dart:1
        working_dir: /app
        depends_on:
            - dart
        ports:
            - ${DART_PORT}:8080
            - 8181:8181
        volumes:
            - '../jikpoze/:/app/'
            - '../.dart-cache/:/root/.pub-cache/'
        command: ['pub', 'serve', '--hostname=0.0.0.0']

    mailcatcher:
        image: zolweb/docker-mailcatcher:latest
        ports:
            - ${MAILCATCHER_PORT}:1080
