# all routes are prefixed with /fire/ (@see app/config/routing.yml)

bluebear.fire.start:
    path: /start
    defaults: {_controller: BlueBearFireBundle:Game:start}

bluebear.fire.new:
    path: /new
    defaults: {_controller: BlueBearFireBundle:Game:new}

bluebear.firegame.run:
    path:     /run/{contextId}
    defaults: {_controller: BlueBearFireBundle:Game:run}
