services:
    bluebear.fire.movement_subscriber:
        class: BlueBear\FireBundle\Event\Subscriber\MovementSubscriber
        tags:
            - {name: kernel.event_subscriber}

    bluebear.fire.eav_configuration_subscriber:
        class: BlueBear\FireBundle\Event\Subscriber\EAVAdminConfigurationSubscriber
        tags:
            - {name: kernel.event_subscriber}

    bluebear.fire.map_generator:
        class: BlueBear\FireBundle\Generator\MapGenerator
        arguments:
            - '@context_repository'
            - '@map_item_repository'
