imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

monolog:
    handlers:
        main:
            type: rotating_file
            max_files: 5
            path: "%kernel.logs_dir%/%kernel.environment%-front.log"
            level: error
