parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Handler\Engine\MovementHandler: ~
    App\Handler\Model\ModelHandler:
        arguments:
            0:
                - '@App\Handler\Engine\MovementHandler'
    App\Contracts\Handler\ModelHandlerInterface: '@App\Handler\Model\ModelHandler'

    App\Factory\Model\Engine\MovementFactory: ~
    App\Factory\Model\ModelFactory:
        arguments:
            0:
                - '@App\Factory\Model\Engine\MovementFactory'
    App\Contracts\Factory\ModelFactoryInterface: '@App\Factory\Model\ModelFactory'
