imports:
    - { resource: managers.yml }
    - { resource: forms.yml }

parameters:
    # 3ngine
    bluebear.engine.engine: BlueBear\EngineBundle\Engine\Engine
    bluebear.engine.context_factory: BlueBear\EngineBundle\Engine\Context\ContextFactory

    # Events Subscribers
    bluebear.engine.event.mapitem_leave_subscriber: BlueBear\EngineBundle\Event\MapItem\MapItemLeaveSubscriber
    bluebear.engine.event.mapitem_subscriber: BlueBear\EngineBundle\Event\Subscriber\MapItemSubscriber
    bluebear.engine.event.map_subscriber: BlueBear\EngineBundle\Event\Subscriber\MapSubscriber
    bluebear.engine.event.engine_subscriber: BlueBear\EngineBundle\Event\Subscriber\EngineSubscriber
    bluebear.engine.event.dynamic_mapping_subscriber: BlueBear\EngineBundle\Event\Subscriber\DynamicMappingSubscriber
    bluebear.engine.event.game_subscriber: BlueBear\EngineBundle\Event\Subscriber\GameSubscriber

    # pathfinder
    bluebear.engine.path_finder: BlueBear\EngineBundle\Path\PathFinder

    # ruler
    bluebear.engine.ruler: BlueBear\EngineBundle\Rules\Ruler

    # entity type factory
    bluebear.game.entity_type_factory: BlueBear\EngineBundle\Factory\EntityTypeFactory

    # Context utilities
    bluebear.engine.context.utilities.class: BlueBear\EngineBundle\Engine\ContextUtilities

    # Doctrine class dynamic loading of EntityInstance
    bluebear.listener.doctrine_event_listener.class: BlueBear\EngineBundle\Listener\DoctrineEventListener

services:
    # engine
    bluebear.engine.engine:
        class: %bluebear.engine.engine%
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setSerializer, [@jms_serializer]]
            - [setAllowedEvents, [%bluebear.engine.events%]]

    # Events Subscribers
    bluebear.engine.event.mapitem_subscriber:
        class: %bluebear.engine.event.mapitem_subscriber%
        tags:
            - {name: kernel.event_subscriber}
        calls:
            - [setContainer, [@service_container]]

    bluebear.engine.event.map_subscriber:
        class: %bluebear.engine.event.map_subscriber%
        tags:
            - {name: kernel.event_subscriber}
        calls:
            - [setContextFactory, [@bluebear.engine.context_factory]]
            - [setContainer, [@service_container]]

    bluebear.engine.event.engine_subscriber:
        class: %bluebear.engine.event.engine_subscriber%
        tags:
            - {name: kernel.event_subscriber}
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setContextManager, [@bluebear.manager.context]]

    bluebear.engine.event.game_subscriber:
        class: %bluebear.engine.event.game_subscriber%
        tags:
            - {name: kernel.event_subscriber}
        calls:
            - [setContainer, [@service_container]]

    bluebear.kernel.terminate.listener:
         class: BlueBear\EngineBundle\Listener\KernelTerminateEventListener
         tags:
           - { name: kernel.event_listener, event: kernel.terminate, method: terminate }

    # ContextFactory
    bluebear.engine.context_factory:
        class: %bluebear.engine.context_factory%
        calls:
            - [setMapManager, [@bluebear.manager.map]]
            - [setDoctrine, [@doctrine]]

    # pathfinder
    bluebear.engine.path_finder:
        class: %bluebear.engine.path_finder%
        calls:
            - [setRuler, [@bluebear.engine.ruler]]

    # ruler
    bluebear.engine.ruler:
        class: %bluebear.engine.ruler%

    # factory
    bluebear.game.entity_type_factory:
        class: %bluebear.game.entity_type_factory%
        calls:
            - [createEntityTypes, [%bluebear.game.entity_type%, %bluebear.game.attribute%, %bluebear.game.behaviors%]]

    bluebear.engine.context.utilities:
        class: %bluebear.engine.context.utilities.class%

    bluebear.listener.doctrine_event_listener:
        class: %bluebear.listener.doctrine_event_listener.class%
        arguments: [@bluebear.game.entity_type_factory]
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
