# BlueBear Engine
blue_bear_engine:
    events:
        bluebear.chess.select:
            request: BlueBear\GameChessBundle\Event\Request\SelectRequest
            response: BlueBear\GameChessBundle\Event\Response\SelectResponse
    game:
        entity_type:
            piece:
                label: Piece
                description: Chess piece
                behaviors: [selectable]
            pawn:
                label: Pawn
                parent: piece
                description: Pawn
            rook:
                label: Rook
                parent: piece
                description: Rook
            bishop:
                label: Bishop
                parent: piece
                description: Bishop
            knight:
                label: Knight
                parent: piece
                description: Knight
            queen:
                label: Queen
                parent: piece
                description: Queen
            king:
                label: King
                parent: piece
                description: King
        # entity behaviors (and their associated event to listen)
        behaviors:
            selectable: bluebear.chess.select
