# BlueBear Engine
blue_bear_engine:
    events:
        bluebear.engine.mapLoad:
            request: BlueBear\EngineBundle\Event\Request\MapLoadRequest
            response: BlueBear\EngineBundle\Event\Response\MapLoadResponse
        bluebear.chess.select:
            request: BlueBear\GameChessBundle\Event\Request\SelectRequest
            response: BlueBear\EngineBundle\Event\Response\MapUpdateResponse
    game:
        entity_type:
            chess_piece:
                label: Piece
                description: Chess piece
                behaviors: [selectable]
                class: BlueBear\GameChessBundle\Entity\Piece
            chess_pawn:
                label: Pawn
                parent: chess_piece
                description: Pawn
            chess_rook:
                label: Rook
                parent: chess_piece
                description: Rook
            chess_bishop:
                label: Bishop
                parent: chess_piece
                description: Bishop
            chess_knight:
                label: Knight
                parent: chess_piece
                description: Knight
            chess_queen:
                label: Queen
                parent: chess_piece
                description: Queen
            chess_king:
                label: King
                parent: chess_piece
                description: King
        # entity behaviors (and their associated event to listen)
        behaviors:
            selectable: bluebear.chess.select
