bluebear.chess.play:
    path:     /play
    defaults: { _controller: BlueBearGameChessBundle:Game:play }

bluebear.chess.joinGame:
    path:     /joinGame
    defaults: { _controller: BlueBearGameChessBundle:Game:joinGame }
