services:
    chess.listeners.select:
        class: BlueBear\GameChessBundle\Event\Listener\SelectListener
        tags:
            - {name: kernel.event_listener, event: bluebear.chess.select, method: onSelect}

#    chess.rules.pawn:
#        class: RuleSet
#        tags:
#            - {name: bluebear.rules, domain: pawn}
