parameters:
    chess.engine.context.utilities.class: BlueBear\GameChessBundle\Event\ChessContextUtilities

services:
    chess.listeners.select:
        class: BlueBear\GameChessBundle\Event\Listener\SelectListener
        arguments: [@chess.engine.context.utilities]
        tags:
            - {name: kernel.event_listener, event: bluebear.chess.select, method: onSelect}

    chess.engine.context.utilities:
        class: %chess.engine.context.utilities.class%
        arguments: [@bluebear.manager.entity_instance]
