services:
#    blue_bear_game_chess.example:
#        class: BlueBear\GameChessBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    chess.rules.pawn:
        class: RuleSet
        tags:
            - {name: bluebear.rules, domain: pawn}