blue_bear_backoffice_homepage:
    pattern:  /
    defaults: {_controller: BlueBearBackofficeBundle:Main:homepage}

blue_bear_backoffice_image:
    pattern: /images
    defaults: { _controller: BlueBearBackofficeBundle:Image:index }

blue_bear_backoffice_image_upload:
    pattern: /upload
    defaults: { _controller: BlueBearBackofficeBundle:Image:upload }