# homepage
bluebear.homepage:
    path:  /
    defaults: {_controller: 'BlueBearBackofficeBundle:Main:homepage'}

# Tests for API
bluebear_backoffice_api:
    path: /tests
    defaults: { _controller: 'BlueBearBackofficeBundle:Api:index' }

bluebear_backoffice_api_scenario:
    path: /tests/scenarios
    defaults: { _controller: 'BlueBearBackofficeBundle:Api:scenario' }

# User
bluebear.user.create:
    path: /user/create
    defaults: {_controller: 'BlueBearBackofficeBundle:User:create'}
