# homepage
bluebear_backoffice_homepage:
    pattern:  /
    defaults: {_controller: BlueBearBackofficeBundle:Main:homepage}

# Tests for API
bluebear_backoffice_api:
    pattern: /tests
    defaults: { _controller: BlueBearBackofficeBundle:Api:index }

bluebear_backoffice_api_scenario:
    pattern: /tests/scenarios
    defaults: { _controller: BlueBearBackofficeBundle:Api:scenario }
