# homepage
bluebear_backoffice_homepage:
    pattern:  /
    defaults: {_controller: BlueBearBackofficeBundle:Main:homepage}

# Tests
bluebear_backoffice_api:
    pattern: /tests
    defaults: { _controller: BlueBearBackofficeBundle:Api:index }

# Documentation
bluebear_backoffice_documentation:
    pattern: /docs
    defaults: { _controller: BlueBearBackofficeBundle:Documentation:index }