bluebear_backoffice_homepage:
    pattern:  /
    defaults: {_controller: BlueBearBackofficeBundle:Main:homepage}


# Images
bluebear_backoffice_image:
    pattern: /images
    defaults: { _controller: BlueBearBackofficeBundle:Image:index }

bluebear_backoffice_image_upload:
    pattern: /upload
    defaults: { _controller: BlueBearBackofficeBundle:Image:upload }

bluebear_backoffice_image_orphans:
    pattern: /images/orphans
    defaults: { _controller: BlueBearBackofficeBundle:Image:listOrphans }

bluebear_backoffice_image_edit:
    pattern: /images/edit/{id}
    defaults: { _controller: BlueBearBackofficeBundle:Image:edit }



# Pencils
bluebear_backoffice_pencil:
    pattern: /pencils
    defaults: { _controller: BlueBearBackofficeBundle:Pencil:index }

bluebear_backoffice_pencil_edit:
    pattern: /pencils/edit
    defaults: { _controller: BlueBearBackofficeBundle:Pencil:edit }

bluebear_backoffice_pencil_delete:
    pattern: /pencils/delete/{id}
    defaults: { _controller: BlueBearBackofficeBundle:Pencil:delete }

bluebear_backoffice_pencil_set_edit:
    pattern: /pencils/addPencilSet
    defaults: { _controller: BlueBearBackofficeBundle:Pencil:editPencilSet }

bluebear_backoffice_pencil_set_delete:
    pattern: /pencils/deletePencilSet/{id}
    defaults: { _controller: BlueBearBackofficeBundle:Pencil:deletePencilSet }

bluebear_backoffice_select_pencil_set:
    pattern: pencils/selectPencilSet
    defaults: { _controller: BlueBearBackofficeBundle:Pencil:selectPencilSet }


# Layers
bluebear_backoffice_layer:
    pattern: /layers
    defaults: { _controller: BlueBearBackofficeBundle:Layer:index }

bluebear_backoffice_layer_edit:
    pattern: /layers/edit
    defaults: { _controller: BlueBearBackofficeBundle:Layer:edit }

bluebear_backoffice_layer_delete:
    pattern: /layers/delete/{id}
    defaults: { _controller: BlueBearBackofficeBundle:Layer:delete }



# Units
bluebear_backoffice_units:
    pattern: /units
    defaults: { _controller: BlueBearBackofficeBundle:Unit:index }


# Map
bluebear_backoffice_map:
    pattern: /maps
    defaults: { _controller: BlueBearBackofficeBundle:Map:index }

bluebear_backoffice_map_edit:
    pattern: /maps/edit
    defaults: { _controller: BlueBearBackofficeBundle:Map:edit }

bluebear_backoffice_map_delete:
    pattern: /map/delete/{id}
    defaults: { _controller: BlueBearBackofficeBundle:Map:delete }