bluebear_backoffice_homepage:
    pattern:  /
    defaults: {_controller: BlueBearBackofficeBundle:Main:homepage}

# Images
bluebear_backoffice_image:
    pattern: /images
    defaults: { _controller: BlueBearBackofficeBundle:Image:index }

bluebear_backoffice_image_upload:
    pattern: /upload
    defaults: { _controller: BlueBearBackofficeBundle:Image:upload }

bluebear_backoffice_image_orphans:
    pattern: /images/orphans
    defaults: { _controller: BlueBearBackofficeBundle:Image:listOrphans }

bluebear_backoffice_image_edit:
    pattern: /images/edit/{id}
    defaults: { _controller: BlueBearBackofficeBundle:Image:edit }
###

# Pencils
bluebear_backoffice_pencil:
    pattern: /pencils
    defaults: { _controller: BlueBearBackofficeBundle:Pencil:index }

# Pencils
bluebear_backoffice_pencil_create:
    pattern: /pencils/create
    defaults: { _controller: BlueBearBackofficeBundle:Pencil:create }

bluebear_backoffice_pencil_edit:
    pattern: /pencils/edit/{id}
    defaults: { _controller: BlueBearBackofficeBundle:Pencil:edit }