parameters:
    bluebear.twig.utils: BlueBear\CoreBundle\Twig\UtilsExtension

services:
    webhotel.twig.utils:
        class: %bluebear.twig.utils%
        tags:
            - {name: twig.extension }
        calls:
            - [setContainer, [@service_container]]