services:
    bluebear.form.login_handler:
        class: BlueBear\BackofficeBundle\Form\Handler\LoginFormHandler
        arguments:
            - '@security.password_encoder'
            - '@user_repository'
